spring:

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      graphql:
        graphiql:
          enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/resources_controller
    username: root
    password: 4785375f
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      schema: controller
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

enabled: true




