spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/resources_controller
    username: root
    password: 4785375f
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      schema: controller