spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/resources_controller
    username: admin
    password: 121911
    driverClassName: org.postgresql.Driver
    hikari:
      schema: controller
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true